import type { CommentItem, DemoUser, FeedPost, Product, Story } from "@/lib/types";

export const demoUsers: DemoUser[] = [
  {
    id: "user-sarah",
    name: "Sarah Style",
    username: "sarah_style",
    email: "sarah@example.com",
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=160&q=80",
    bio: "Fashion creator sharing daily finds.",
    role: "CREATOR",
  },
  {
    id: "user-urban",
    name: "Urban Explorer",
    username: "urban_explorer",
    email: "urban@example.com",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80",
    bio: "Travel, coffee, and city essentials.",
    role: "CREATOR",
  },
  {
    id: "user-cozy",
    name: "Cozy Corner",
    username: "cozy_corner",
    email: "cozy@example.com",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=80",
    bio: "Home decor for slower evenings.",
    role: "VENDOR",
  },
  {
    id: "user-photo",
    name: "Photo Journey",
    username: "photo_journey",
    email: "photo@example.com",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=160&q=80",
    bio: "Golden-hour portraits and gear notes.",
    role: "CREATOR",
  },
  {
    id: "user-healthy",
    name: "Healthy Eats",
    username: "healthy_eats",
    email: "healthy@example.com",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=160&q=80",
    bio: "Simple food that fits real mornings.",
    role: "CREATOR",
  },
  {
    id: "user-demo",
    name: "Demo Customer",
    username: "demo_customer",
    email: "demo@example.com",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=160&q=80",
    role: "CUSTOMER",
  },
];

export const demoProducts: Product[] = [
  {
    id: "product-dress",
    vendorId: "user-sarah",
    name: "Summer Dress",
    slug: "summer-dress",
    description: "A light floral dress made for warm days and social shoots.",
    shortDescription: "Green floral summer dress",
    images: ["https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=600&q=80"],
    category: "Fashion",
    price: 49.99,
    originalPrice: 69.99,
    discountPercent: 29,
    stockQuantity: 18,
    sku: "SUM-DRESS-001",
    status: "ACTIVE",
    tags: ["summer", "fashion"],
    vendorName: "sarah_style",
  },
  {
    id: "product-jacket",
    vendorId: "user-urban",
    name: "Denim Jacket",
    slug: "denim-jacket",
    description: "Structured denim jacket for travel days and casual city looks.",
    shortDescription: "Classic travel denim jacket",
    images: ["https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80"],
    category: "Fashion",
    price: 89.99,
    stockQuantity: 9,
    sku: "DEN-JACKET-002",
    status: "ACTIVE",
    tags: ["denim", "travel"],
    vendorName: "urban_explorer",
  },
  {
    id: "product-candle",
    vendorId: "user-cozy",
    name: "Scented Candle",
    slug: "scented-candle",
    description: "Warm amber candle for cozy evenings and gifting.",
    shortDescription: "Amber scented candle",
    images: ["https://images.unsplash.com/photo-1602874801006-e26cf8ae8630?auto=format&fit=crop&w=600&q=80"],
    category: "Home",
    price: 24.99,
    originalPrice: 35,
    discountPercent: 20,
    stockQuantity: 30,
    sku: "CANDLE-003",
    status: "ACTIVE",
    tags: ["home", "decor"],
    vendorName: "cozy_corner",
  },
  {
    id: "product-bowl",
    vendorId: "user-healthy",
    name: "Ceramic Bowl",
    slug: "ceramic-bowl",
    description: "Small glazed bowl for breakfast bowls and dessert plating.",
    shortDescription: "Glazed ceramic bowl",
    images: ["https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?auto=format&fit=crop&w=600&q=80"],
    category: "Kitchen",
    price: 15.99,
    stockQuantity: 0,
    sku: "BOWL-004",
    status: "OUT_OF_STOCK",
    tags: ["foodie", "kitchen"],
    vendorName: "healthy_eats",
  },
];

export const demoPosts: FeedPost[] = [
  {
    id: "post-summer",
    slug: "summer-vibes-green-dress",
    creator: demoUsers[0],
    caption: "Summer vibes with this amazing outfit! ☀️",
    hashtags: ["summer", "fashion"],
    media: [{ url: "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=900&q=85", type: "image", width: 900, height: 900 }],
    product: demoProducts[0],
    likeCount: 1200000,
    commentCount: 4500,
    shareCount: 904,
  },
  {
    id: "post-urban",
    slug: "city-walks-denim-jacket",
    creator: demoUsers[1],
    caption: "City walks and coffee talks ☕",
    hashtags: ["citylife", "ootd"],
    media: [{ url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85", type: "image", width: 900, height: 900 }],
    product: demoProducts[1],
    likeCount: 850000,
    commentCount: 2100,
    shareCount: 320,
  },
  {
    id: "post-cozy",
    slug: "cozy-evening-essentials",
    creator: demoUsers[2],
    caption: "Cozy evening essentials 🕯️",
    hashtags: ["home", "decor"],
    media: [{ url: "https://images.unsplash.com/photo-1602874801006-e26cf8ae8630?auto=format&fit=crop&w=900&q=85", type: "image", width: 900, height: 900 }],
    product: demoProducts[2],
    likeCount: 2100000,
    commentCount: 10000,
    shareCount: 1750,
  },
  {
    id: "post-photo",
    slug: "golden-hour-aesthetics",
    creator: demoUsers[3],
    caption: "Golden hour aesthetics ✨",
    hashtags: ["photography", "goldenhour"],
    media: [{ url: "https://images.unsplash.com/photo-1512316609839-ce289d3eba0a?auto=format&fit=crop&w=900&q=85", type: "image", width: 900, height: 900 }],
    likeCount: 450000,
    commentCount: 1200,
    shareCount: 188,
  },
  {
    id: "post-breakfast",
    slug: "healthy-breakfast-bowls",
    creator: demoUsers[4],
    caption: "Healthy breakfast ideas for busy mornings 🥑",
    hashtags: ["foodie", "health"],
    media: [{ url: "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?auto=format&fit=crop&w=900&q=85", type: "image", width: 900, height: 900 }],
    product: demoProducts[3],
    likeCount: 320000,
    commentCount: 800,
    shareCount: 97,
  },
];

export const demoStories: Story[] = demoUsers.slice(0, 5).map((creator, index) => ({
  id: `story-${creator.username}`,
  creator,
  mediaUrl: index === 0 ? "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=85" : demoPosts[index]?.media[0]?.url ?? "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=900&q=85",
  viewed: index % 2 === 1,
  product: demoProducts[index % demoProducts.length],
}));

export const demoComments: CommentItem[] = [
  {
    id: "comment-1",
    postId: "post-cozy",
    user: demoUsers[2],
    text: "Amazing look",
    likeCount: 32,
    createdAt: new Date().toISOString(),
  },
  {
    id: "comment-2",
    postId: "post-cozy",
    user: { ...demoUsers[5], username: "user_123", name: "User 123" },
    text: "Love this style",
    likeCount: 19,
    createdAt: new Date().toISOString(),
  },
  {
    id: "comment-3",
    postId: "post-cozy",
    user: { ...demoUsers[5], username: "maria", name: "Maria" },
    text: "Where can I buy?",
    likeCount: 11,
    createdAt: new Date().toISOString(),
  },
];

export const getDemoPostBySlug = (slug: string) => demoPosts.find((post) => post.slug === slug);
export const getDemoProductBySlug = (slug: string) => demoProducts.find((product) => product.slug === slug);
